# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Air Quality: Kampala
email: m.t.smith@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Air Quality Kampala: Monitoring the air you breath
baseurl: "air-quality-kampala/"
url: "https://lionfish0.github.io" # the base hostname & protocol for your site
twitter_username: mikethomassmith
github_username:  lionfish0 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
